old_sound_rabbit_mq:
    connections:
        default:
            url: 'amqp://admin:admin@localhost:5672?lazy=1&connection_timeout=6'
    producers:
        task:
            connection: default
            exchange_options: { name: 'send.exchange', type: 'direct' }
        delay:
            connection: default
            exchange_options: { name: 'delay.exchange', type: 'x-delayed-message', arguments: {'x-delayed-type': ['S', 'direct'] }}
    consumers:
        task:
            connection: default
            exchange_options: { name: 'send.exchange', type: 'direct' }
            queue_options:
                name: 'send.sms.queue'
            callback: App\Consumer\SmsConsumer
        delay:
            connection: default
            exchange_options: { name: 'delay.exchange', type: 'x-delayed-message', arguments: {'x-delayed-type': ['S', 'direct'] }}
            queue_options:
                name: 'sms.delayed'
            callback: App\Consumer\BlankConsumer
